name: gutie43
favicon: null
layout_spectrum: 0.95259
typography_spectrum: 0.08685628115199506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8acc4'
    - '#d5d9dc'
    - '#1a1c1b'
    - '#716966'
    - '#703e27'
  brandStrength: 0.11806435976177454
  lightness: 0.5961347629781812
  saturation: 0.263075593393296
  rhythmicContrast: 0.75
purpose: []
