typography_spectrum: 0.08685628115199506
color:
  brandColors:
    - '#a8acc4'
    - '#d5d9dc'
    - '#1a1c1b'
    - '#716966'
    - '#703e27'
  brandStrength: 0.11806435976177454
  lightness: 0.5961347629781812
  saturation: 0.263075593393296
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.95259
analytics:
  google: null
  facebook: null
  twitter: null
name: gutie43
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Raising the bar...
purpose: []
